Fix title and description fallbacks for news and events
hofff/contao-social-tags pull request #5
Opened 2020-09-01 17:47 UTC by fritzmg

This PR fixes the following things for the News and Event Extractor:

* The _extract…Description_ methods used `description` as the fallback. However, that field is only available in Contao **4.9+**, but not in Contao **4.4**. This PR uses the `description` field as the first fallback if present and otherwise generates the description from the `teaser` the same way as Contao does.
* The _extract…Title_ methods only used the `title`/`headline` as the fallback. However, in Contao **4.9+** we also have the `pageTitle` field for news and events, which will be used for the meta information instead. This PR uses the `pageTitle` field as the first fallback if present and otherwise falls back to the `title`/`headline`.

I can undo the sorting of the use statements again if necessary (it's just my IDE that did it automatically).

2020-09-02 06:22 UTC, dmolineus commented
> I can undo the sorting of the use statements again if necessary (it's just my IDE that did it automatically).

Yes, pleas follow the coding standards which are checked by PHP Code Sniffer only so far. Just run `vendor/bin/phpcs` after a composer install. You might use `vendor/bin/phpcbf` to use the auto fix feature of phpcs.

2020-09-02 07:50 UTC, fritzmg commented
Ah thank you, I was unfamiliar with how to use phpcs to auto-fix, will do 👍

2020-09-02 13:04 UTC, dmolineus commented
> Ah thank you, I was unfamiliar with how to use phpcs to auto-fix, will do +1

Yeah the naming is counter intuitive. Will use `phpcq` v2 when I'll find some time for it. :-)

2020-09-07 14:03 UTC, dmolineus requested changes

2020-09-07 14:03 UTC, dmolineus commented on src/Data/Extractor/CalendarEventsExtractor.php
> +        return $this->replaceInsertTags($model->pageTitle ?: $model->title);
Please keep the `TypeUtil::isStringWithContent()` check. It ensures that an empty string will return null and no empty tags will be createded. The methode would look like:

```php
$title = $model->pageTitle ?: $model->title;
if (TypeUtil::isStringWithContent($title)) {	
    return $this->replaceInsertTags($title);	
}

return null;
```

2020-09-07 14:03 UTC, dmolineus commented on src/Data/Extractor/NewsExtractor.php
> +        return $this->replaceInsertTags($model->pageTitle ?: $model->headline);
Please keep the `TypeUtil::isStringWithContent()` check. It ensures that an empty string will return null and no empty tags will be createded. The methode would look like:

```php
$title = $model->pageTitle ?: $model->headline;
if (TypeUtil::isStringWithContent($title)) {	
    return $this->replaceInsertTags($title);	
}

return null;
```

2020-09-07 14:13 UTC, fritzmg commented on src/Data/Extractor/CalendarEventsExtractor.php
> +        return $this->replaceInsertTags($model->pageTitle ?: $model->title);
To be honest, I did not quite get the point of `TypeUtil::isStringWithContent`: https://3v4l.org/LDhF6 - what other cases does `TypeUtil::isStringWithContent` cover?

2020-09-07 14:16 UTC, fritzmg commented on src/Data/Extractor/CalendarEventsExtractor.php
> +        return $this->replaceInsertTags($model->pageTitle ?: $model->title);
Ah, well it disregards anything that is not a `string` of course, but for example a non-empty object or array: https://3v4l.org/iLStM

But are you sure this type of check is necessary?

2020-09-07 14:17 UTC, dmolineus commented on src/Data/Extractor/CalendarEventsExtractor.php
> +        return $this->replaceInsertTags($model->pageTitle ?: $model->title);
https://3v4l.org/1o6Pi

2020-09-07 14:45 UTC, dmolineus commented on src/Data/Extractor/CalendarEventsExtractor.php
> +        return $this->replaceInsertTags($model->pageTitle ?: $model->title);
I want to make sure that an empty string will return `null`. The extractor is consumed from the `DataFactory` which creates `Data` objects for it. For optional tags, it's required that `null` is return, as anything else than `null` is treated as existing.

The extractor is furthermore not responsible to decide if a tag is required or not which is the job of the implementation of the `DataFactory`.

2020-09-07 15:59 UTC, fritzmg commented
PR is now updated with using `TypeUtil::isStringWithContent` both for the title and description for news and events.

2020-09-09 06:06 UTC, merged

2020-09-09 06:07 UTC, dmolineus commented
Thanks @fritzmg