Fix URL generation for faq, news & events
hofff/contao-social-tags pull request #6
Opened 2020-09-02 09:01 UTC by fritzmg

Currently the URL generated for faq, news and events is not necessarily an absolute URL, since `News::generateNewsUrl` uses `getFrontendUrl` and not `getAbsoluteUrl` - and `getFrontendUrl` only returns an absolute URL, if the current domain differs from the generated domain.

This PR prepends the scheme and host if the generated URL is not absolute.

2020-09-02 12:59 UTC, dmolineus commented
Ah, I see that feature to force an absolute url was added in Contao 4.5 and is not available in Contao 4.4.

2020-09-07 14:06 UTC, dmolineus requested changes

2020-09-07 14:06 UTC, dmolineus commented on src/Data/Extractor/FaqExtractor.php
> +        $faqUrl = News::generateNewsUrl($faqModel, false, true);
This is a bug in the current implementation. The news class can't generate a proper url for faqs. Would you mind to have a look on it?

2020-09-07 14:10 UTC, fritzmg commented on src/Data/Extractor/FaqExtractor.php
> +        $faqUrl = News::generateNewsUrl($faqModel, false, true);
I don't think this is a bug - I think you deliberately use `News::generateNewsUrl` for everything, because it happens to work with everything :). The function has not strict type on the `NewsModel` and its implementation is also independent of the actual model class. It's quite a ingenious mis-use 😁.

2020-09-07 14:54 UTC, fritzmg commented
As discussed in Slack I have updated the PR, adding a static function to generate the FAQ url, similar to how the other functions work.

2020-09-09 06:10 UTC, merged

2020-09-09 06:10 UTC, dmolineus commented
Thanks @fritzmg